FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir streamlit plotly pandas httpx streamlit-autorefresh pyvis networkx streamlit-aggrid

COPY dashboard ./dashboard

ENV PYTHONPATH=/app

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0", "--theme.base=dark"]
